version: '3.6'
services:
  big-dipper-2:
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        NEXT_PUBLIC_GRAPHQL_URL: ${NEXT_PUBLIC_GRAPHQL_URL}
        NEXT_PUBLIC_GRAPHQL_WS: ${NEXT_PUBLIC_GRAPHQL_WS}
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
        NEXT_PUBLIC_WS_CHAIN_URL: ${NEXT_PUBLIC_WS_CHAIN_URL}
        NEXT_PUBLIC_CHAIN_STATUS: ${NEXT_PUBLIC_CHAIN_STATUS}
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
    restart: always
    ports:
      - "3000:3000"
    logging:
    driver: "gcplogs"
