[context.privnet.environment]
NEXT_PUBLIC_GRAPHQL_WS = "wss://explorer-gql.private-testnet.cudos.org/v1/graphql"
NEXT_PUBLIC_URL = "https://explorer.private-testnet.cudos.org/"
NEXT_PUBLIC_GRAPHQL_URL = "https://explorer-gql.private-testnet.cudos.org/v1/graphql"
NEXT_PUBLIC_CHAIN_STATUS = "testnet"
NEXT_PUBLIC_WS_CHAIN_URL = "wss://sentry-01.hosts.private-testnet.cudos.org:36657/websocket"

[context.testnet.environment]
NEXT_PUBLIC_GRAPHQL_WS = "wss://explorer-gql.testnet.cudos.org/v1/graphql"
NEXT_PUBLIC_URL = "https://explorer.testnet.cudos.org"
NEXT_PUBLIC_GRAPHQL_URL = "https://explorer-gql.testnet.cudos.org/v1/graphql"
NEXT_PUBLIC_CHAIN_STATUS = "testnet"
NEXT_PUBLIC_WS_CHAIN_URL = "wss://sentry3.gcp-euwest4.cudos.org:36657/websocket"

[context.mainnet.environment]
NEXT_PUBLIC_GRAPHQL_WS = "wss://explorer-gql.cudos.org/v1/graphql"
NEXT_PUBLIC_URL = "https://explorer.cudos.org"
NEXT_PUBLIC_GRAPHQL_URL = "https://explorer-gql.cudos.org/v1/graphql"
NEXT_PUBLIC_CHAIN_STATUS = "mainnet"
NEXT_PUBLIC_WS_CHAIN_URL = "wss://mainnet-full-node-01.hosts.cudos.org:36657/websocket"
