name: Test
on:
  pull_request:
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --legacy-peer-deps
    - name: Run lint check
      run: npm run lint
  Unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci --legacy-peer-deps
    - name: Run tests
      run: npm test -- --coverage
    # - name: Upload coverage 📤
    #   uses: codecov/codecov-action@v1
    #   with:
    #     file: coverage/lcov.info
    #     fail_ci_if_error: true
  Build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci --legacy-peer-deps
    - name: Run build check
      run: npm run build
      env:
          NODE_OPTIONS: "--max-old-space-size=8192"
